//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_New_Paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Cart
    {
        public int Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public double Total_Price { get; set; }
        public int Total_Quantity { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
