//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_New_Paradise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Employee_ID { get; set; }
        [Display(Name = "Styler")]
        public string Employee_Name { get; set; }
        [Display(Name = "Contact Number")]
        public string Employee_Phone { get; set; }
        [Display(Name = "Email")]
        public string Employee_Email { get; set; }
        [Display(Name = "Salary")]
        public double Employee_Salary { get; set; }
        [Display(Name = "Working from(in years)")]
        public int Employee_Experience { get; set; }
    }
}
